name: Retrieve Secret
on:
  workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret in hex
        run: |
          echo "${{ secrets.RELEASE_KEY_PASSWORD }}" | xxd -p -c 0